# Generated by Django 5.1.7 on 2025-05-09 06:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_profile_options_profile_profile_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtherDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(blank=True, max_length=100)),
                ('avg_hours', models.CharField(blank=True, max_length=100)),
                ('time_period', models.CharField(blank=True, max_length=100)),
                ('strength', models.CharField(blank=True, max_length=255)),
                ('style', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name': 'OtherDetail',
                'verbose_name_plural': 'OtherDetails',
                'ordering': ['id'],
            },
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='username',
            new_name='status',
        ),
        migrations.AddField(
            model_name='profile',
            name='tagline',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='other',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.otherdetail'),
        ),
    ]
