# Generated by Django 5.1.7 on 2025-11-19 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_lesson_note'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='lesson',
        ),
        migrations.RemoveField(
            model_name='note',
            name='user',
        ),
        migrations.DeleteModel(
            name='Lesson',
        ),
        migrations.DeleteModel(
            name='Note',
        ),
    ]
