# Generated by Django 5.1.7 on 2025-11-22 18:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_note_lesson_remove_note_user_delete_lesson_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassAnalyticsSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('class_name', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('avg_score', models.FloatField(default=0.0)),
                ('distribution', models.JSONField(blank=True, default=dict)),
                ('common_difficulties', models.JSONField(blank=True, default=list)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SystemMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('metric_type', models.CharField(choices=[('response_time', 'Response Time'), ('rag_accuracy', 'RAG Accuracy'), ('user_satisfaction', 'User Satisfaction'), ('feature_usage', 'Feature Usage')], max_length=50)),
                ('value', models.FloatField(default=0.0)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Competency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subject', models.CharField(max_length=150)),
                ('topic', models.CharField(max_length=255)),
                ('level', models.FloatField(default=0.0)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competencies', to='app.profile')),
            ],
            options={
                'unique_together': {('profile', 'subject', 'topic')},
            },
        ),
        migrations.CreateModel(
            name='CompetencyHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('level', models.FloatField(default=0.0)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('competency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='app.competency')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EngagementMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session_date', models.DateField()),
                ('duration_seconds', models.IntegerField(default=0)),
                ('interactions', models.IntegerField(default=0)),
                ('interaction_depth', models.FloatField(default=0.0)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='engagements', to='app.profile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InterventionFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subject', models.CharField(max_length=150)),
                ('topic', models.CharField(blank=True, max_length=255)),
                ('reason', models.TextField(blank=True)),
                ('flagged_at', models.DateTimeField(auto_now_add=True)),
                ('resolved', models.BooleanField(default=False)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interventions', to='app.profile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LearningStyleProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('current_style', models.CharField(blank=True, max_length=100)),
                ('confidence', models.FloatField(default=0.0)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='learning_style', to='app.profile')),
            ],
            options={
                'verbose_name': 'LearningStyleProfile',
                'verbose_name_plural': 'LearningStyleProfiles',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='LearningStyleHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('style', models.CharField(max_length=100)),
                ('confidence', models.FloatField(default=0.0)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('learning_style', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='app.learningstyleprofile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PerformanceTrend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subject', models.CharField(max_length=150)),
                ('topic', models.CharField(blank=True, max_length=255)),
                ('score', models.FloatField(default=0.0)),
                ('recorded_at', models.DateField()),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_trends', to='app.profile')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
