# Generated by Django 5.1.7 on 2025-11-25 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_profile_profile_image_profile_social_links_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='learning_styles',
            field=models.JSONField(blank=True, default=dict, help_text='Learning style dimensions: active_reflective, sensing_intuitive, visual_verbal, sequential_global (-11 to +11)'),
        ),
    ]
