# Generated by Django 5.1.7 on 2025-12-10 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_profile_learning_styles'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='manual_adjustments',
            field=models.JSONField(blank=True, default=dict, help_text='Manual learning style adjustments set by user from Settings page (-11 to +11)'),
        ),
        migrations.AddField(
            model_name='profile',
            name='manual_adjustments_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='manual_adjustments_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
