# Generated by Django 4.2.7 on 2026-02-18 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_profile_manual_adjustments_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='manual_adjustments',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='manual_adjustments_completed',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='manual_adjustments_timestamp',
        ),
    ]
