# Generated by Django 4.2.7 on 2026-03-04 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_remove_profile_manual_adjustments_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='last_learning_style_update',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='manual_adjustments',
            field=models.JSONField(blank=True, default=dict, help_text='Manual learning style adjustments set by user from Settings page (-11 to +11)'),
        ),
        migrations.AddField(
            model_name='profile',
            name='manual_adjustments_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='questionnaire_completed',
            field=models.BooleanField(default=False),
        ),
    ]
