# Generated by Django 5.1.7 on 2025-11-18 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_make_document_session_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_good',
            field=models.BooleanField(default=False, help_text='Marks if this message is a good response'),
        ),
    ]
