# Generated by Django 5.1.7 on 2025-11-19 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0002_alter_lesson_options_lesson_content_and_more'),
    ]

    operations = [
    ]
