# Generated by Django 5.1.7 on 2025-11-19 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0003_alter_note_options_remove_lesson_content_and_more'),
    ]

    operations = [
    ]
