# Generated by Django 5.1.7 on 2025-11-19 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0004_lesson_content_alter_note_id_alter_topic_order'),
    ]

    operations = [
    ]
