# Generated by Django 4.2.7 on 2026-02-28 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0005_grade_subject_lesson_subject'),
    ]

    operations = [
    ]

