# Generated by Django 4.2.7 on 2026-03-01 08:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0006_alter_note_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='lessons.lesson'),
        ),
    ]
