# Generated by Django 4.2.7 on 2026-03-01 20:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


def reconcile_lessons_tables(apps, schema_editor):
    """
    Ensure core tables exist before creating TopicDiscussion.
    This handles cases where migrations were marked as applied but tables are missing in the DB.
    It ALSO handles the case where the user originally deployed with Integer primary keys
    for lessons and notes, but later changed the codebase to use UUIDs without a proper migration.
    """
    from django.db import connection
    tables = connection.introspection.table_names()
    
    # Check if lessons_lesson has the wrong ID type (bigint instead of uuid)
    with connection.cursor() as cursor:
        if 'lessons_lesson' in tables:
            cursor.execute("SELECT data_type FROM information_schema.columns WHERE table_name = 'lessons_lesson' AND column_name = 'id';")
            result = cursor.fetchone()
            if result and result[0] != 'uuid':
                print("WARNING: lessons_lesson has incorrect primary key type (not uuid). Dropping table to recreate.")
                cursor.execute("DROP TABLE IF EXISTS lessons_topic CASCADE")
                cursor.execute("DROP TABLE IF EXISTS lessons_note CASCADE")
                cursor.execute("DROP TABLE IF EXISTS lessons_lesson CASCADE")
                tables.remove('lessons_lesson')
                if 'lessons_note' in tables: tables.remove('lessons_note')
                if 'lessons_topic' in tables: tables.remove('lessons_topic')

    # Check for Lesson table
    if 'lessons_lesson' not in tables:
        print("Creating missing table: lessons_lesson")
        Lesson = apps.get_model('lessons', 'Lesson')
        schema_editor.create_model(Lesson)
    
    # Check for Note table
    if 'lessons_note' not in tables:
        print("Creating missing table: lessons_note")
        Note = apps.get_model('lessons', 'Note')
        schema_editor.create_model(Note)
        
    # Check for Topic table
    if 'lessons_topic' not in tables:
        print("Creating missing table: lessons_topic")
        Topic = apps.get_model('lessons', 'Topic')
        schema_editor.create_model(Topic)

class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lessons', '0007_alter_note_lesson'),
    ]

    operations = [
        migrations.RunPython(reconcile_lessons_tables, reverse_code=migrations.RunPython.noop),
        migrations.CreateModel(
            name='TopicDiscussion',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='lessons.topicdiscussion')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discussions', to='lessons.topic')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_discussions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Topic Discussion',
                'verbose_name_plural': 'Topic Discussions',
                'ordering': ['created_at'],
            },
        ),
    ]
