# Generated by Django 4.2.7 on 2026-03-01 20:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lessons', '0007_alter_note_lesson'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopicDiscussion',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='lessons.topicdiscussion')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discussions', to='lessons.topic')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_discussions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Topic Discussion',
                'verbose_name_plural': 'Topic Discussions',
                'ordering': ['created_at'],
            },
        ),
    ]
