# Generated by Django 5.1.7 on 2025-05-08 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_id',
            field=models.CharField(default='profile_id', max_length=100),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
