# Generated by Django 5.1.7 on 2025-05-11 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_created_at_user_updated_at_alter_user_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='dp_img',
            field=models.ImageField(blank=True, null=True, upload_to='images/profile_img/testuser.jpeg'),
        ),
    ]
