# Generated by Django 5.1.7 on 2025-05-11 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_dp_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='dp_img',
        ),
    ]
