# Generated by Django 4.2.7 on 2026-02-19 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_is_email_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
